### ISSUE TITLE
Question about writing row by row with variable column content length

### ISSUE THREAD

**Issue by JonCook** [nom-tam-fits/nom-tam-fits#89] opened 2016-04-04 15:25 UTC
Hi,

This was a question if you could provide a simple example of writing a TableDataset row by row but with the possibility of having variable column lengths.

I have been reading here - http://nom-tam-fits.github.io/nom-tam-fits/intro.html and it makes reference to using FitsHeap directly but I don't quite see how.

What would be great if anyone has time is to create a simple example of creating a table with columns and then writing row by row.

Thanks very much.
Jon

**Comment by wcleveland** [comment] 2016-04-07 14:09
Hi,

I haven't tried the low level stuff. I just add the columns into an object array and use FitsFactory to create a TableHDU.

I'll try it out when I'm not busy with work and post a better example. Give me a couple of days.

Bill

**Comment by JonCook** [comment] 2016-04-08 09:59
OK, that would be great. I'm investigating the possibility to write row by row in real time without necessarily knowing upfront how many rows and also the content could be variable length in the columns so I don't want to have to set a limit upfront. For this reason I think I would need to use the FitsHeap object. It would be really great to have a simple example of how one might do this. Thanks Jon

**Comment by wcleveland** [comment] 2016-04-11 18:02
FITS is a sequential file format and you'll have to know the numbers of rows ahead of time before writing the file.

Since you were looking at the low-level examples, I went ahead and made a version that actually works here: [LowLevelTables.java.zip](https://github.com/nom-tam-fits/nom-tam-fits/files/213550/LowLevelTables.java.zip)

Variable length rows would be much harder and the page you link mentions this:

 "Since data with variable length records have each row written to at least two different places in the FITS files (the table main data and the table heap), streaming writes of these tables is harder. The methods of FitsHeap can be used but unless there’s a real need it’s a lot easier just to use the higher level methods for writing these."

**Comment by JonCook** [comment] 2016-04-11 20:26
many thanks. I will take a look. It looks like a good start. It is a shame that variable length isn't obvious from the code/examples. The problem is if you have one long String in a row in a column it means all the other rows are padded to the same length and results in a very bloated file size. This is my understanding.

**Comment by wcleveland** [comment] 2016-04-11 21:28
That is correct. The documentation mentions doing variable length records using the high level method and I'll look into it during my next free time.

**Comment by JonCook** [comment] 2016-04-12 12:53
If you have some free time soon that would be really useful. Thanks.

**Comment by ritchieGitHub** [comment] 2016-04-24 08:28
@JonCook I am back in again, row by row writing is not "usefull" with the current implementation. It's very inefficient to do it row by row, better to store the whole table at once. It is planned that it will be possible in version 2.x because we will support tables of unlimmited size (only your disk space is a limit ;-) )

**Comment by ritchieGitHub** [comment] 2016-05-22 05:29
Because there is no more "talk", the issue is closed

**Comment by MaxNoe** [comment] 2016-08-09 20:22
Really, you closed an unsolved issue because there is no more talk?

Sorry, but that's just odd. I stumbled upon the same problem and seing this issue under the open open ones would have spared me some time.

See also #98

**Comment by MaxNoe** [comment] 2016-08-09 20:29
@wcleveland Many thanks for your working example on how to write sequentially.

**Comment by ritchieGitHub** [comment] 2016-08-12 16:58
nice example, thanks. This is a nice "trick" to bypass the shortcomings of the library. There will be a much better support for this kind of tasks in the 2.0 version (in planning). I closed the issue because it will not be fixed in any way. Maybe we should add some faq somewhere...

**Comment by ritchieGitHub** [comment] 2016-08-12 17:00
I think this will do, just made a milestone questions and added this one as a open question

**Comment by MaxNoe** [comment] 2016-08-12 17:04
To see some "real world application" ,  see https://github.com/fact-project/fact-tools/blob/78700650e71f185d91f58dcd181709cdd0512904/src/main/java/fact/io/FITSWriter.java

**Comment by attipaci** [comment] 2021-11-17 01:51
I assume this issue can be closed now. If not, feel free to reopen.

**Closed by attipaci** 2021-11-17 01:51 UTC
Labels: question
