### ISSUE TITLE
Using Random Access Fits file read fails?

### ISSUE THREAD

**Issue by mabula117** [nom-tam-fits/nom-tam-fits#116] opened 2017-06-08 10:41 UTC
Hi there,

For just reading the FITS headers of files I use:

fitsFile = new Fits(imageFile);

with imageFile a Java File object

in an try catch construction. 

I understand that nom.tam.fits uses a java Random Access file to read the file in this construction.

This works great and quick for lots of big FITS files.

However If I try to use this Random Access construction for actual loading of the FITS files, the loading fails for a lot of them. I have to use

InputStream fileStream = new BufferedInputStream(new FileInputStream(imageFile), bufferSize);
Fits fitsFile = new Fits(fileStream);

Is this normal behaviour? Wouldn't Random Access read be better or faster as well? Or doesn't it matter for the speed of  the actual reading of the FITS files?

The error I get with random access read

java.io.IOException: Stream Closed
	at java.io.RandomAccessFile.seek0(Native Method)
	at java.io.RandomAccessFile.seek(RandomAccessFile.java:557)
	at nom.tam.util.BufferedFile.seek(BufferedFile.java:591)
	at nom.tam.image.StandardImageTiler.getCompleteImage(StandardImageTiler.java:304)
	at nom.tam.fits.ImageData.getData(ImageData.java:170)
	at nom.tam.fits.Data.getKernel(Data.java:114)
	at nom.tam.fits.BasicHDU.getKernel(BasicHDU.java:393)
	at imageLoaders.FitsLinearImageLoaderTask.doInBackground(FitsLinearImageLoaderTask.java:715)

I am using Java 1.8.0_121 and nom.tam.fits nom-tam-fits-1.15.2-20161112.063922-9.jar

Kind regards,
Mabula

**Comment by ritchieGitHub** [comment] 2017-06-08 10:58
I will take a look tomorrow

**Comment by ritchieGitHub** [comment] 2017-06-09 09:47
please send some example images, this is not the normal behaviour. Random access should always be possible. you can upload files in a pull request of the backbox images repository. or you provide a download link.

**Comment by mabula117** [comment] 2017-06-09 12:31
Thanks Ritchie,

Here are three FITS files which can't be loaded with the Random Access file construction, but do load with the BufferedInputStream:

https://www.astropixelprocessor.com/wp-content/uploads/2017/06/16bits-RGB-M45_100mmF2_8_ISO200_300sSeries512-exp_007-Patrick-Duis.zip

https://www.astropixelprocessor.com/wp-content/uploads/2017/06/PetraVanDerMeijs-astroforum-sadr__001.zip

https://www.astropixelprocessor.com/wp-content/uploads/2017/06/16bits-RGB-compressed-ScottRosen-450D-03h-80dec-C_CVT_2013-12-29-MW1-03h_Light_600SecISO200_000042.zip


Sources are Nebulosity and Images Plus.

I used the following coder for these fits files:

Fits fitsFile = null;
try {
	//InputStream fileStream = new BufferedInputStream(new FileInputStream(imageFile), bufferSize);
	//fitsFile = new Fits(fileStream);
	
	fitsFile = new Fits(imageFile); // uses a Random Acces File
	
	fitsFileHDU = fitsFile.read(); //get all HDUs from this fits File and get entire stream
				
	fitsFile.close();
	fitsFile = null;
	
	//fileStream.close();		
	//fileStream = null;
	
} catch (PaddingException e3) {

} catch etc...

Feel free to add these images to the test images.

Kind regards,
Mabula

**Comment by ritchieGitHub** [comment] 2017-06-09 13:48
in my system everything is working as expected. all files loaded without problem. lets see if it is something specific.
- have you tried the released version (I see you use an old snapshot version) 1.15.2 is released and available from central.
- are the images loaded form a special drive or network share?

**Comment by mabula117** [comment] 2017-06-09 15:11
Hi Ritchie,

I upgraded to the latest release 1.15.2. Nothing changed.

I tried to check if it's related to my try catch construct, it seems to be the case..

If I code like this: 

Fits fitsFile = null;
try {
	
	fitsFile = new Fits(imageFile); // uses a Random Acces File, is much quicker !!! than bufferedStream
	
	fitsFileHDU = fitsFile.read(); //get all HDUs from this fits File and get entire stream
				
	//fitsFile.close();
	//fitsFile = null;
	
	
} catch (PaddingException e3) {
	// if images aren't correctly padded, iNOVA batchprocess
	// we can still read the HDUs properly
	// this exception is there to indicate, that these files are wrongly created
	
	try {
		
		fitsFile.addHDU(e3.getTruncatedHDU());
		fitsFileHDU = fitsFile.read(); // read again all HDUs including the truncated HDU
		
	} catch (FitsException e) {
		
		FitsExceptionHandler.showFitsException(e, imageFile);
		this.cancel(true);
	}
	
	
} catch (FitsException e1) {
	
	//System.out.println("here1" + System.lineSeparator() + e1);
	
	FitsExceptionHandler.showFitsException(e1, imageFile);
	this.cancel(true);
	
} 

All the files work with Random Access

But if I do:

Fits fitsFile = null;
try {
	
	fitsFile = new Fits(imageFile); // uses a Random Acces File, is much quicker !!! than bufferedStream
	// much quicker, but fails with lots of FITS files...
	
	fitsFileHDU = fitsFile.read(); //get all HDUs from this fits File and get entire stream
				
	fitsFile.close();
	fitsFile = null;
	
	
} catch (PaddingException e3) {
	// if images aren't correctly padded, iNOVA batchprocess
	// we can still read the HDUs properly
	// this exception is there to indicate, that these files are wrongly created
	
	try {
		
		fitsFile.addHDU(e3.getTruncatedHDU());
		fitsFileHDU = fitsFile.read(); // read again all HDUs including the truncated HDU
		
	} catch (FitsException e) {
		
		FitsExceptionHandler.showFitsException(e, imageFile);
		this.cancel(true);
	}
	
	
} catch (FitsException e1) {
	
	//System.out.println("here1" + System.lineSeparator() + e1);
	
	FitsExceptionHandler.showFitsException(e1, imageFile);
	this.cancel(true);
	
} catch (IOException e2) {
	
	//System.out.println("here2" + System.lineSeparator() + e2);
	
	IOExceptionHandler.showFITSIOException(e2, imageFile);
	this.cancel(true);
	
}
 
So I close the Fits fitsFile after done reading, I need to add another catch (IOException) and this is where it then fails. Can you reproduce this?

I am using java 8, but sill with an old format for try catch and closing I guess maybe I should do it following The try-with-resources Statement? : 
https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html

The working code above would lead to a resource leak I would think so it can't be a good solution?

Mabula

**Comment by ritchieGitHub** [comment] 2017-06-11 05:13
I will try this, probably this evening. Java-8 and old style try catches (try resources) can not be the problem ;) They are translated in the same type of byte code as you wrote it explicitly.

**Comment by mabula117** [comment] 2017-06-12 18:41
Hi Ritchie,

Yes indeed.

Can you close in on this problem, or is it a strange one?

I am developing on Windows 7 Pro in the eclipse IDE. 

Mabula

**Comment by ritchieGitHub** [comment] 2017-06-13 06:42
my problem is time ;-) To be fair I think this week will be difficult, I hope for the weekend ;-)
or is it very urgent? then I will try to squeeze it somewhere between tasks..

**Comment by mabula117** [comment] 2017-06-15 14:10
Hi Ritchie, no not very urgent, but I hope you can find the reason for this behaviour.
 
Are there known problem of FITS reads from external drives with certain filesystems by any chance?

Mabula

**Comment by ritchieGitHub** [comment] 2017-06-15 14:17
no, no open issues in that area. but it is a initial suspisiin


-------- Originalnachricht --------
Betreff: Re: [nom-tam-fits/nom-tam-fits] Using Random Access Fits file read fails? (#116)
Von: mabula117 
An: nom-tam-fits/nom-tam-fits 
Cc: "van Nieuwenhoven, Richard" ,Assign 




Hi Ritchie, no not very urgent, but I hope you can find the reason for this behaviour.
Are there known problem of FITS reads from external drives with certain filesystems by any chance?
Mabula
—
You are receiving this because you were assigned.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.






{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/nom-tam-fits/nom-tam-fits","title":"nom-tam-fits/nom-tam-fits","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/nom-tam-fits/nom-tam-fits"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mabula117 in #116: Hi Ritchie, no not very urgent, but I hope you can find the reason for this behaviour.\r\n \r\nAre there known problem of FITS reads from external drives with certain filesystems by any chance?\r\n\r\nMabula"}],"action":{"name":"View Issue","url":"https://github.com/nom-tam-fits/nom-tam-fits/issues/116#issuecomment-308745205"}}}

**Comment by attipaci** [comment] 2021-11-17 01:50
Hi Mabula,

I somehow slipped over this one before. I'm not sure what the problem is but I encountered similar ones when I used try-with-resources constructs, and did not pay attention to the fact that these close the file/stream at the end of the block, whether there is an exception or not. So, when you try to access the stream from a wrapper object later, you end up with the kind of error you see. My guess, is that somewhere in your code you unintentionally close the file (or the Fits that wraps it, or Fits.getStream()), and this is why the error happens.

Let me know if this is an issue still, and we can dig deeper. Otherwise, I'll close this ticket shortly...

cheers,

-- A.

**Closed** 2021-11-21 02:24 UTC
Labels: question
