### ISSUE TITLE
String value length limitation?

### ISSUE THREAD

**Issue by supermartzin** [nom-tam-fits/nom-tam-fits#11] opened 2015-04-06 10:42 UTC
Hi,
I've got another case of strange behaviour when saving **string value** to header card:
```java
HeaderCard card = new HeaderCard("KEYWORD", "v", "comment of FITS header card with length of exactly 64 characters");
```
Whole header card should have now length of **80** characters - **10** for ```KEYWORD˽=˽```, **3** for ```'v'```, another **3** for ```˽/˽``` and remaining **64** for comment value ```comment of FITS header card with length of exactly 64 characters```
Nevertheless header card is saved to header as this:
```
KEYWORD = 'v       '           / comment of FITS header card with length of exac
```

I'm not aware of any length limitation for string values in FITS file specification so is this an expected behaviour?

Thanks :)

**Comment by ritchieGitHub** [comment] 2015-04-06 11:12
Thats a question for @TomMcGlynn  he is the fits expert. I do not know bis availability durring the Eastern hollidays so his answer can have a little tatency.

**Comment by supermartzin** [comment] 2015-04-06 11:13
Okay, thanks.

**Comment by TomMcGlynn** [comment] 2015-04-06 13:48
If I understand the issue, supermartzin is concerned with two distinct issues:
  - A short string value 'v' was right padded to 8 characters long
  - A comment string that would have fit in space left in the FITS header card was truncated
because blank padding was inserted after the keyword value and before the comment.

FITS header cards may be in either fixed or free format.  Fixed point format requires that strings be padded to at least 8 characters with the value (i.e., the initial ') in column 12. It also mandates that non-string values are written with the value right aligned in column 30.  Free format header records can have shorter strings and allow values to be placed more freely in the 80 characters.  Fixed format is required for mandatory keywords.  It was also the case -- at least early in the lifetime of this library -- that some software could not read free format records.  They were not allowed in the earliest versions of the standard.

To ensure maximum readability of the data, the library writes all records in fixed format (though
it should be able to read free format records).   To keep comments nicely aligned, comments
are normally started in column 32 since the non-string comments cannot start till then (with the
values terminating in column 30).

It would be possible to support writing of free format records.  I can't recall offhand if the library translates free format records into fixed format when copying a file, but one could add a flag in the HeaderCard class if this was actually causing a problem (as opposed to being an unexpected feature).

**Comment by supermartzin** [comment] 2015-04-06 14:10
Thanks for the explanation, I was aware of the alignment to column 30 with non-string values but couldn'd find anything like that also for string values.

**Comment by TomMcGlynn** [comment] 2015-04-06 14:24
Martin Vrábel wrote:
>
> Thanks for the explanation, I was aware of the alignment to column 30 
> with non-string values but couldn'd find anything like that also for 
> string values.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nom-tam-fits/nom-tam-fits/issues/11#issuecomment-90077668>.
>
I believe you are correct that it would be perfectly legal to start the 
comment earlier for string values.   My personal experience is that I 
actually read FITS headers a fair bit [just set the terminal width to 80 
and cat the file] and having the comments aligned is a real benefit.  
But this choice was probably made 15 years ago or more, so you should 
let us know if it's time to reconsider it.

     Tom

**Comment by ritchieGitHub** [comment] 2015-04-06 16:21
Maybe it would be good to try to allign the String but if the comment would not fit then go without alignment?

**Comment by supermartzin** [comment] 2015-04-07 08:43
Sounds good but if it should break the compatibility with older specification I would stay with alignment.

**Comment by TomMcGlynn** [comment] 2015-04-07 12:33
Richard van Nieuwenhoven wrote:
>
> Maybe it would be good to try to allign the String but if the comment 
> would not fit then go without alignment?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nom-tam-fits/nom-tam-fits/issues/11#issuecomment-90130041>.
>
This would be fine as an option, but I think it would be a mistake to 
make it the default.  Other people using the library will see the 
contents of their files change and regression tests may fail.  If there 
were a significant benefit it might be worth inflicting that pain but
regardless of this choice, the API silently truncates comments at some 
length, the only question is do we allow short string to have slightly 
longer comments.

**Comment by ritchieGitHub** [comment] 2015-04-17 05:15
ok, send it to milestone 2.0.0 there are more changes there, so I thing we can inflict some pain there.

**Comment by ritchieGitHub** [comment] 2015-04-18 04:19
@supermartzin how soon do you need a release, or is the snapshot good enough?

**Comment by supermartzin** [comment] 2015-04-18 07:52
Yeah, snapshot is enough so far so you don't need to rush the release :)

**Comment by ritchieGitHub** [comment] 2015-05-05 04:39
@supermartzin do you have time to test a new implementation of the longstring stuff. I could generate a new snapshot and you check if your features are still there ;-)
The longstring stuff is reimplemented as a single card in the library, so your program would support it automatically.

**Comment by supermartzin** [comment] 2015-05-05 08:06
Of course, pleasure to try it :)
So if I want to create new longstring HeaderCard I just do it like any other card?

**Comment by ritchieGitHub** [comment] 2015-05-06 03:58
ok, it is deployed. The use of longstrings is now automatic (just use long strings ;-) ) and set the support flag to true (FitsFactory)

**Comment by supermartzin** [comment] 2015-05-06 10:14
Just to be sure after testing it, it supports only long string **values**, not **comments**, right? So the allowed comment value remains still maximum *47 characters*.

**Comment by supermartzin** [comment] 2015-05-06 10:22
Probably found a small pullback.
When I allow use of long strings and try to following card:
```java
HeaderCard card = new HeaderCard("LONGSTR", "This is very very very very very very very very very very very very very very very very very very very very very very very very very very very long string value of FITS card", "long longer longest comment");
```
it won't trim the comment as usual but creates something like this in header:
```
LONGSTR = 'This is very very very very very very very very very very very very&'
CONTINUE  ' very very very very very very very very very very very very very v&'
CONTINUE  'ery very long string value of FITS card' / long longer longest commen
t
```
and mess up with image data of FITS file.

**Comment by ritchieGitHub** [comment] 2015-05-06 10:25
yes, but a little longer comments are now supported when they fit. But they are still trimmed silently for backward compatibility. If a string is a long string the comment may now be a little longer because it can use the comment space of two cards. More space for comments will have to be moved to 2.0.0 where more of the API and behaviour will change.

During my writing you found a bug, very good! That's why I asked, because I knew you would find at least one .... tomorrow morning there will be a next snapshot, thanks!

**Comment by ritchieGitHub** [comment] 2015-05-06 15:02
just published a new SNAPSHOT, please try it again.

**Comment by ritchieGitHub** [comment] 2015-05-14 04:57
@supermartzin everything ok now?

**Comment by supermartzin** [comment] 2015-05-14 10:24
Sorry for my delay, I wasn't able to try it until yesterday.

So I tried again te same value as described above and the result is this:
```
LONGSTR = 'This is very very very very very very very very very very very very&'
CONTINUE  ' very very very very very very very very very very very very very v&'
CONTINUE  'ery very long string value of FITS &' / long longer longest comment
CONTINUE  'card'
```
I would expect to write it like this:
```
LONGSTR = 'This is very very very very very very very very very very very very&'
CONTINUE  ' very very very very very very very very very very very very very v&'
CONTINUE  'ery very long string value of FITS card' / long longer longest comme&
CONTINUE  nt
``` 
Then I changed comment to ```long longer longest loooongest comment``` and the resultant card was:
```
LONGSTR = 'This is very very very very very very very very very very very very&'
CONTINUE  ' very very very very very very very very very very very very very v&'
CONTINUE  'ery very long string value of FITS &' / long longer longest loooonges
CONTINUE  'card' / t comment
```

I don't understand the positioning and division of comment.

**Comment by ritchieGitHub** [comment] 2015-05-14 11:10
That is correct. Comments can not be prolonged with to a next line that's why  I now split the string a little sooner so more of the comment will fit. Super, I will close this issue now. Lets see what more to include next version.

**Closed by ritchieGitHub** 2015-05-14 11:10 UTC
Labels: enhancement, question

**Comment by supermartzin** [comment] 2015-05-14 11:38
Okay, it just seems to me a bit confusing and worse readable, especially the longer comment.

**Comment by ritchieGitHub** [comment] 2015-05-14 11:52
yes, but that's where the bug was. When you try to fit in that example in one line you will notice that one character of the comment does not fit ... but as soon as you split the string just a little bit the comment fits in the first line. Seems strange but as you see the only solution to keep the comment whole. Of course I could move the complete comment to the last line, but that would complicate the algorithm a lot...
