### ISSUE TITLE
Wierd bug adding whitespace to comment with each header edit

### ISSUE THREAD

**Issue by supermartzin** [nom-tam-fits/nom-tam-fits#12] opened 2015-04-07 15:11 UTC
I found another bug probably.
Each time I edit the header of FITS file (adding, editing or removing cards), one new whitespace is added to each comment of header card.
I started with this header:
```
Image #1
    SIMPLE  =                    T
    BITPIX  =                   16
    NAXIS   =                    2
    NAXIS1  =                 1530
    NAXIS2  =                 1020
    EXPOSURE=  0.14000000000000000
    TEMPERAT= -14.8000000000000000
    DATE-OBS= '2012-04-20T16:16:12.1' / UT
    JD      =  2456038.17791800000
    DATE-LOC= '2012-04-20T18:16:12.1' / LT
    FILTER  = 'V-photom 1.00'
    XPIXSZ  =                  9.0
    YPIXSZ  =                  9.0
    AVISUMIN=                102.0
    AVISUMAX=                130.0
    AVISUTYP=                  0.0
```
After successfull adding and removing some random `HeaderCard` for 3 times, header looks like this:
```
Image #1
    SIMPLE  =                    T
    BITPIX  =                   16
    NAXIS   =                    2
    NAXIS1  =                 1530
    NAXIS2  =                 1020
    EXPOSURE=  0.14000000000000000
    TEMPERAT= -14.8000000000000000
    DATE-OBS= '2012-04-20T16:16:12.1' /       UT
    JD      =  2456038.17791800000
    DATE-LOC= '2012-04-20T18:16:12.1' /       LT
    FILTER  = 'V-photom 1.00'
    XPIXSZ  =                  9.0
    YPIXSZ  =                  9.0
    AVISUMIN=                102.0
    AVISUMAX=                130.0
    AVISUTYP=                  0.0
```
Notice comments for `DATE-OBS` and `DATE-LOC` cards. They got exactly 6 more starting whitespaces (before - **1**, after - **7**).

I guess it's some kind of bug in the code, can you confirm it?
Thanks :)

**Comment by ritchieGitHub** [comment] 2015-04-08 04:34
your are great, big thanks for finding and taking your time to report these issues, keep up the good job! They will definitely improve the quality for these "special" cases ;-)

**Comment by supermartzin** [comment] 2015-04-08 09:52
Please, are you able to fix this particular issue and release a fixed version (for example **1.12.1**)? As the new major release won't be released soon I need to use version **1.12.0** and this bug is serious for me as I can't get around it in my own.
I would really appreciate it. 
Thanks! :)

**Comment by ritchieGitHub** [comment] 2015-04-08 10:31
ok for me, this weekend ok? @TomMcGlynn do you concur?

**Comment by supermartzin** [comment] 2015-04-08 10:52
Perfect, thanks! ;-)

**Comment by ritchieGitHub** [comment] 2015-04-08 11:19
I will try to delver a "SNAPSHOT" version tomorrow morning (Vienna time), so you can test it befor we release.

**Comment by TomMcGlynn** [comment] 2015-04-08 19:18
I can see how this happens.  The space after the / that defines the beginning of the comment is not required, so in principle the comment that the library reads back starts with a space.  Then when it gets written out again the formatting space is reapplied...

Presumably the formatting space should not be written if the comment begins with a space.  I don't think we want to trim the comment.  Users may use lots of initial spaces in a comment to do
some kind of formatting.

**Comment by ritchieGitHub** [comment] 2015-04-09 04:32
it collides with some other features (long strings) so i need a little more time. i must postpone the "SNAPSHOT" to tomorrow, sorry.

**Comment by supermartzin** [comment] 2015-04-09 09:36
Nevermind, thank you anyway for taking time to fix it for me :)

**Comment by ritchieGitHub** [comment] 2015-04-10 05:52
It should be fixed, please try it from the snapshot:

```xml
	<dependencies>
		<dependency>
			<groupId>gov.nasa.gsfc.heasarc</groupId>
			<artifactId>nom-tam-fits</artifactId>
			<version>1.12.1-SNAPSHOT</version>
		</dependency>
	</dependencies>
	<repositories>
		<repository>
			<id>sonatype-snapshots</id>
			<url>https://oss.sonatype.org/content/repositories/snapshots</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
	</repositories>  
```

**Comment by supermartzin** [comment] 2015-04-10 11:51
Thanks, the bug seems to be gone :)

**Closed** 2015-04-17 05:12 UTC
Labels: bug

**Comment by sfoale** [comment] 2015-06-17 09:42
One of our users has spotted this too so it's great that the issue is already fixed - thanks.

Any chance of a release with this fix being deployed so we can just pull it from the maven repository?

**Comment by ritchieGitHub** [comment] 2015-06-17 10:07
for the next 2-4 weeks use the snapshot repository, then we should be ready for a release (1.13.0)

**Comment by sfoale** [comment] 2015-06-17 12:36
Thanks.
